name: healthrag
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - boto3=1.40.54=py314hca03da5_0
  - botocore=1.40.54=py314hca03da5_1
  - bottleneck=1.4.2=py314hdbb4bc7_1
  - brotlicffi=1.2.0.0=py314h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.11.12=py314hca03da5_0
  - cffi=2.0.0=py314h73c2a22_1
  - charset-normalizer=3.4.4=py314hca03da5_0
  - click=8.2.1=py314hca03da5_1
  - cyrus-sasl=2.1.28=h0121217_3
  - idna=3.11=py314hca03da5_0
  - jmespath=1.0.1=py314hca03da5_0
  - kagglehub=0.3.13=py314hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libkrb5=1.21.3=h73ed823_4
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libpq=17.6=h479fd88_0
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numexpr=2.14.1=py314h4402d01_0
  - numpy=2.3.5=py314hde9b8b7_0
  - numpy-base=2.3.5=py314hb4b2851_0
  - openldap=2.6.10=h6d5b105_1
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py314hca03da5_1
  - pandas=2.3.3=py314heb7d0cc_1
  - pip=25.3=pyh0d26453_0
  - psycopg2=2.9.11=py314h08ee000_0
  - pycparser=2.23=py314hca03da5_0
  - pysocks=1.7.1=py314hca03da5_1
  - python=3.14.2=h1858270_101_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python-dotenv=1.1.0=py314hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314hca03da5_0
  - pyyaml=6.0.3=py314h091b9d3_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py314hca03da5_1
  - s3transfer=0.14.0=py314hca03da5_0
  - six=1.17.0=py314hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tqdm=4.67.1=py314h7136c26_1
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/homebrew/anaconda3/envs/healthrag
